export interface Tool {
  id: string;
  name: string;
  nameKo: string;
  description: string;
  url: string;
  category: string;
  categoryIcon: string;
  difficulty: 1 | 2 | 3;
  hasFree: boolean;
  tags: string[];
  color: string;
}

export const categories = ['대화형 AI', '이미지 생성', '영상/오디오', '문서/글쓰기', '업무 생산성', '코딩/개발', '하드웨어/설계', '논문/연구'];

export const tools: Tool[] = [
  // 대화형 AI
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    nameKo: '챗GPT',
    description: '가장 유명한 대화형 AI. 코딩, 글쓰기, 번역 등 거의 모든 작업이 가능합니다.',
    url: 'https://chat.openai.com',
    category: '대화형 AI',
    categoryIcon: '🤖',
    difficulty: 1,
    hasFree: true,
    tags: ['만능', '대화형', '필수도구'],
    color: 'from-emerald-600 to-teal-800',
  },
  {
    id: 'claude',
    name: 'Claude',
    nameKo: '클로드',
    description: '자연스러운 한국어 구사와 긴 문서 분석에 특화된 AI. 프로그래밍과 글쓰기에 뛰어납니다.',
    url: 'https://claude.ai',
    category: '대화형 AI',
    categoryIcon: '🧠',
    difficulty: 1,
    hasFree: true,
    tags: ['문서분석', '글쓰기', '코딩'],
    color: 'from-amber-600 to-orange-800',
  },
  {
    id: 'gemini',
    name: 'Gemini',
    nameKo: '제미나이',
    description: '구글이 만든 AI. 구글 워크스페이스(문서, 드라이브)와 연동되며 최신 정보 검색이 빠릅니다.',
    url: 'https://gemini.google.com',
    category: '대화형 AI',
    categoryIcon: '✨',
    difficulty: 1,
    hasFree: true,
    tags: ['구글연동', '최신정보', '무료'],
    color: 'from-blue-600 to-indigo-800',
  },
  {
    id: 'copilot',
    name: 'Microsoft Copilot',
    nameKo: '마이크로소프트 코파일럿',
    description: '마이크로소프트의 AI. 무료로 GPT-4와 이미지 생성 기능(DALL-E 3)을 사용할 수 있습니다.',
    url: 'https://copilot.microsoft.com',
    category: '대화형 AI',
    categoryIcon: '🚀',
    difficulty: 1,
    hasFree: true,
    tags: ['무료GPT4', '이미지생성', '빙검색'],
    color: 'from-sky-500 to-blue-700',
  },
  {
    id: 'poe',
    name: 'Poe',
    nameKo: '포',
    description: 'ChatGPT, Claude, Gemini 등 다양한 AI 모델들을 한 곳에서 골라 쓸 수 있는 플랫폼입니다.',
    url: 'https://poe.com',
    category: '대화형 AI',
    categoryIcon: '💬',
    difficulty: 2,
    hasFree: true,
    tags: ['AI모음', '모델비교', '챗봇생성'],
    color: 'from-indigo-500 to-purple-700',
  },

  // 업무 생산성
  {
    id: 'perplexity',
    name: 'Perplexity',
    nameKo: '퍼플렉시티',
    description: '검색 엔진에 특화된 AI. 질문하면 여러 웹사이트를 찾아서 출처와 함께 정확한 답변을 줍니다.',
    url: 'https://www.perplexity.ai',
    category: '업무 생산성',
    categoryIcon: '🔍',
    difficulty: 1,
    hasFree: true,
    tags: ['검색', '논문조사', '출처제공'],
    color: 'from-cyan-600 to-blue-800',
  },

  {
    id: 'zapier',
    name: 'Zapier Central',
    nameKo: '재피어 센트럴',
    description: '수천 개의 앱(지메일, 슬랙 등)을 AI와 연동하여 반복 업무를 자동화해주는 봇입니다.',
    url: 'https://zapier.com/central',
    category: '업무 생산성',
    categoryIcon: '⚡',
    difficulty: 3,
    hasFree: true,
    tags: ['업무자동화', '연동', '봇'],
    color: 'from-orange-500 to-red-600',
  },

  // 이미지 생성
  {
    id: 'midjourney',
    name: 'Midjourney',
    nameKo: '미드저니',
    description: '최고의 퀄리티를 자랑하는 이미지 생성 AI. 디스코드를 통해 텍스트로 명령어를 입력합니다.',
    url: 'https://www.midjourney.com',
    category: '이미지 생성',
    categoryIcon: '🎨',
    difficulty: 3,
    hasFree: false,
    tags: ['고퀄리티', '예술', '디자인'],
    color: 'from-purple-600 to-fuchsia-800',
  },
  {
    id: 'dalle3',
    name: 'DALL-E 3',
    nameKo: '달리 3',
    description: 'ChatGPT 안에서 바로 쓸 수 있는 이미지 생성 AI. 복잡한 명령도 아주 잘 알아듣습니다.',
    url: 'https://chat.openai.com',
    category: '이미지 생성',
    categoryIcon: '🖼️',
    difficulty: 1,
    hasFree: false,
    tags: ['쉽다', 'ChatGPT연동', '스토리보드'],
    color: 'from-rose-600 to-pink-800',
  },
  {
    id: 'leonardo',
    name: 'Leonardo.Ai',
    nameKo: '레오나르도 AI',
    description: '게임 에셋, 캐릭터 디자인 등에 특화된 고퀄리티 무료 제공 이미지 생성 AI입니다.',
    url: 'https://leonardo.ai',
    category: '이미지 생성',
    categoryIcon: '🖌️',
    difficulty: 2,
    hasFree: true,
    tags: ['무료크레딧', '게임아트', '다양한모델'],
    color: 'from-fuchsia-600 to-purple-900',
  },

  // 영상/오디오
  {
    id: 'suno',
    name: 'Suno AI',
    nameKo: '수노 AI',
    description: '가사와 스타일만 적으면 전문가 수준의 보컬이 들어간 완벽한 노래를 만들어줍니다.',
    url: 'https://suno.com',
    category: '영상/오디오',
    categoryIcon: '🎵',
    difficulty: 1,
    hasFree: true,
    tags: ['작곡', '음악생성', '보컬'],
    color: 'from-yellow-500 to-orange-600',
  },
  {
    id: 'udio',
    name: 'Udio',
    nameKo: '우디오',
    description: 'Suno의 대항마로 떠오른 고품질 음악 생성 AI. 악기 소리와 보컬이 매우 선명합니다.',
    url: 'https://www.udio.com',
    category: '영상/오디오',
    categoryIcon: '🎧',
    difficulty: 1,
    hasFree: true,
    tags: ['고음질', '작곡', '음악생성'],
    color: 'from-blue-500 to-indigo-600',
  },
  {
    id: 'runway',
    name: 'Runway Gen-2',
    nameKo: '런웨이 젠2',
    description: '텍스트나 이미지를 넣으면 고품질의 비디오 영상을 생성해 주는 혁신적인 AI입니다.',
    url: 'https://runwayml.com',
    category: '영상/오디오',
    categoryIcon: '🎥',
    difficulty: 2,
    hasFree: true,
    tags: ['영상생성', '특수효과', '영화'],
    color: 'from-teal-500 to-emerald-700',
  },
  {
    id: 'heygen',
    name: 'HeyGen',
    nameKo: '헤이젠',
    description: '사진 한 장과 텍스트만 있으면 내 목소리와 얼굴로 말하는 진짜 같은 아바타 영상을 만듭니다.',
    url: 'https://www.heygen.com',
    category: '영상/오디오',
    categoryIcon: '👤',
    difficulty: 2,
    hasFree: true,
    tags: ['아바타', '영상제작', '프레젠테이션'],
    color: 'from-violet-500 to-purple-600',
  },

  // 문서/글쓰기
  {
    id: 'notion-ai',
    name: 'Notion AI',
    nameKo: '노션 AI',
    description: '노션 앱 안에서 문서 요약, 글 다듬기, 아이디어 생성을 도와주는 내장 AI입니다.',
    url: 'https://www.notion.so/product/ai',
    category: '문서/글쓰기',
    categoryIcon: '📝',
    difficulty: 2,
    hasFree: false,
    tags: ['노션', '문서요약', '아이디어'],
    color: 'from-stone-600 to-stone-800',
  },
  {
    id: 'gamma',
    name: 'Gamma',
    nameKo: '감마',
    description: '주제만 입력하면 예쁜 디자인의 PPT(프레젠테이션)를 1분 만에 자동으로 만들어줍니다.',
    url: 'https://gamma.app',
    category: '문서/글쓰기',
    categoryIcon: '📊',
    difficulty: 1,
    hasFree: true,
    tags: ['PPT', '발표자료', '디자인'],
    color: 'from-violet-600 to-purple-800',
  },
  {
    id: 'wrtn',
    name: 'Wrtn',
    nameKo: '뤼튼',
    description: '한국어에 특화된 글쓰기 AI. 자기소개서, 블로그 포스팅, 마케팅 문구 등을 잘 써줍니다.',
    url: 'https://wrtn.ai',
    category: '문서/글쓰기',
    categoryIcon: '✍️',
    difficulty: 1,
    hasFree: true,
    tags: ['한국어', '카피라이팅', '무료'],
    color: 'from-pink-500 to-rose-600',
  },

  // 코딩/개발
  {
    id: 'cursor',
    name: 'Cursor',
    nameKo: '커서',
    description: 'AI가 내장된 전 세계 1위 코드 에디터. 코드를 자동으로 짜주고, 버그를 찾아주며, 질문에 답해줍니다.',
    url: 'https://cursor.sh',
    category: '코딩/개발',
    categoryIcon: '💻',
    difficulty: 3,
    hasFree: true,
    tags: ['코딩', '개발자', 'VSCode호환'],
    color: 'from-slate-700 to-slate-900',
  },
  {
    id: 'v0-dev',
    name: 'v0.dev',
    nameKo: '브이제로',
    description: '프롬프트(명령어)만 입력하면 그 자리에서 완성된 형태의 웹 UI와 코드를 만들어줍니다.',
    url: 'https://v0.dev',
    category: '코딩/개발',
    categoryIcon: '✨',
    difficulty: 2,
    hasFree: true,
    tags: ['프론트엔드', 'UI생성', '디자인'],
    color: 'from-zinc-800 to-zinc-950',
  },
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    nameKo: '깃허브 코파일럿',
    description: '가장 널리 쓰이는 AI 개발 도우미. 코드를 치는 순간 다음 줄이나 함수 전체를 귀신같이 완성해 줍니다.',
    url: 'https://github.com/features/copilot',
    category: '코딩/개발',
    categoryIcon: '🐙',
    difficulty: 2,
    hasFree: false,
    tags: ['자동완성', '표준도구', '개발자'],
    color: 'from-gray-700 to-gray-900',
  },

  // 하드웨어/설계
  {
    id: 'flux-ai',
    name: 'Flux.ai',
    nameKo: '플럭스',
    description: '하드웨어 엔지니어를 위한 AI 기반 PCB(회로) 설계 툴. 브라우저에서 회로 배선을 도와주고 조언을 해줍니다.',
    url: 'https://www.flux.ai',
    category: '하드웨어/설계',
    categoryIcon: '⚙️',
    difficulty: 3,
    hasFree: true,
    tags: ['PCB', '회로설계', '하드웨어'],
    color: 'from-blue-700 to-indigo-900',
  },
  {
    id: 'fusion360-gen',
    name: 'Fusion 360 AI',
    nameKo: '퓨전 360 (제너레이티브 디자인)',
    description: '조건(하중, 소재 등)만 입력하면 AI가 가장 튼튼하고 가벼운 3D 모델(외형)을 수백 개 생성해 제안합니다.',
    url: 'https://www.autodesk.com/products/fusion-360/generative-design',
    category: '하드웨어/설계',
    categoryIcon: '📐',
    difficulty: 3,
    hasFree: false,
    tags: ['3D모델링', 'CAD', '기구설계'],
    color: 'from-orange-600 to-red-800',
  },

  // 논문/연구
  {
    id: 'scispace',
    name: 'SciSpace',
    nameKo: '사이스페이스',
    description: '전 세계 논문을 검색하고, PDF를 업로드하면 어려운 수식이나 표까지 AI가 한국어로 쉽게 설명해 줍니다.',
    url: 'https://typeset.io',
    category: '논문/연구',
    categoryIcon: '🔬',
    difficulty: 2,
    hasFree: true,
    tags: ['논문검색', '수식설명', '연구자'],
    color: 'from-emerald-600 to-cyan-800',
  },
  {
    id: 'consensus',
    name: 'Consensus',
    nameKo: '컨센서스',
    description: '연구 논문에 기반한 검색 엔진. 질문을 던지면 관련 논문들의 결론을 모아 "예/아니오"로 명확히 답해줍니다.',
    url: 'https://consensus.app',
    category: '논문/연구',
    categoryIcon: '🎓',
    difficulty: 1,
    hasFree: true,
    tags: ['논문검색', '팩트체크', '근거제시'],
    color: 'from-indigo-500 to-blue-700',
  },
  {
    id: 'chatpdf',
    name: 'ChatPDF',
    nameKo: '챗PDF',
    description: 'PDF 파일을 통째로 업로드한 뒤 파일 내용에 대해 질문하면, 몇 페이지에 있는 내용인지 출처와 함께 답합니다.',
    url: 'https://www.chatpdf.com',
    category: '논문/연구',
    categoryIcon: '📄',
    difficulty: 1,
    hasFree: true,
    tags: ['PDF요약', '문서대화', '대학생'],
    color: 'from-red-500 to-rose-700',
  }
];
