export interface Tool {
  id: string;
  name: string;
  nameKo: string;
  description: string;
  url: string;
  category: string;
  categoryIcon: string;
  difficulty: 1 | 2 | 3;
  hasFree: boolean;
  tags: string[];
  color: string;
  lastReviewed: string; // 콘텐츠 마지막 검토일 (YYYY-MM)
  quickFilters?: string[]; // 빠른 필터 레이블
}

// 모든 카드가 동일한 날짜를 표시하도록 이 파일이 빌드될 때의 연월을 자동 계산
const REVIEWED_AT = new Date().toISOString().slice(0, 7); // e.g. "2026-04"

export const categories = ['대화형 AI', '이미지 생성', '영상/오디오', '문서/글쓰기', '업무 생산성', '코딩/개발', '하드웨어/설계', '논문/연구'];

// 빠른 필터 정의
export const quickFilters = [
  { id: 'free', label: '🆓 무료 플랜', description: '무료 티어가 있는 도구' },
  { id: 'beginner', label: '🌱 입문자용', description: '난이도 1의 쉬운 도구' },
  { id: 'korean', label: '🇰🇷 한국어 강점', description: '한국어에 특화된 도구' },
  { id: 'image', label: '🎨 이미지', description: '이미지 관련 도구' },
  { id: 'code', label: '💻 코딩', description: '코딩/개발 도구' },
  { id: 'video', label: '🎥 영상/오디오', description: '영상·음악 생성 도구' },
];

export const tools: Tool[] = [
  // 대화형 AI
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    nameKo: '챗GPT',
    description: '가장 널리 쓰이는 대화형 AI. 코딩, 글쓰기, 번역 등 거의 모든 작업이 가능하며, 이미지·파일 분석도 지원합니다.',
    url: 'https://chatgpt.com',
    category: '대화형 AI',
    categoryIcon: '🤖',
    difficulty: 1,
    hasFree: true,
    tags: ['만능', '대화형', '필수도구'],
    color: 'from-emerald-600 to-teal-800',
    lastReviewed: REVIEWED_AT,
    quickFilters: ['free', 'beginner'],
  },
  {
    id: 'claude',
    name: 'Claude',
    nameKo: '클로드',
    description: '자연스러운 한국어 구사와 긴 문서 분석에 강한 AI. 신중하고 일관성 있는 답변이 필요한 글쓰기·리뷰 작업에 적합합니다.',
    url: 'https://claude.ai',
    category: '대화형 AI',
    categoryIcon: '🧠',
    difficulty: 1,
    hasFree: true,
    tags: ['문서분석', '글쓰기', '코딩'],
    color: 'from-amber-600 to-orange-800',
    lastReviewed: REVIEWED_AT,
    quickFilters: ['free', 'beginner', 'korean'],
  },
  {
    id: 'gemini',
    name: 'Gemini',
    nameKo: '제미나이',
    description: '구글이 만든 AI. 구글 문서·드라이브와 연동되며, 검색 기반의 최신 정보 답변이 강점입니다.',
    url: 'https://gemini.google.com',
    category: '대화형 AI',
    categoryIcon: '✨',
    difficulty: 1,
    hasFree: true,
    tags: ['구글연동', '최신정보', '무료'],
    color: 'from-blue-600 to-indigo-800',
    lastReviewed: REVIEWED_AT,
    quickFilters: ['free', 'beginner'],
  },
  {
    id: 'copilot',
    name: 'Microsoft Copilot',
    nameKo: '마이크로소프트 코파일럿',
    description: '마이크로소프트의 AI 어시스턴트. 웹 검색과 이미지 생성을 결합해 사용할 수 있으며, 무료 플랜으로 다양한 기능을 제공합니다.',
    url: 'https://copilot.microsoft.com',
    category: '대화형 AI',
    categoryIcon: '🚀',
    difficulty: 1,
    hasFree: true,
    tags: ['이미지생성', '빙검색', '무료'],
    color: 'from-sky-500 to-blue-700',
    lastReviewed: REVIEWED_AT,
    quickFilters: ['free', 'beginner'],
  },
  {
    id: 'poe',
    name: 'Poe',
    nameKo: '포',
    description: 'ChatGPT, Claude, Gemini 등 다양한 AI 모델들을 한 곳에서 골라 비교하며 쓸 수 있는 멀티 AI 플랫폼입니다.',
    url: 'https://poe.com',
    category: '대화형 AI',
    categoryIcon: '💬',
    difficulty: 2,
    hasFree: true,
    tags: ['AI모음', '모델비교', '챗봇생성'],
    color: 'from-indigo-500 to-purple-700',
    lastReviewed: REVIEWED_AT,
    quickFilters: ['free'],
  },

  // 업무 생산성
  {
    id: 'perplexity',
    name: 'Perplexity',
    nameKo: '퍼플렉시티',
    description: '검색에 특화된 AI. 질문하면 여러 웹사이트를 탐색해 출처와 함께 정확한 답변을 줍니다. 논문·뉴스 조사에 유용합니다.',
    url: 'https://www.perplexity.ai',
    category: '업무 생산성',
    categoryIcon: '🔍',
    difficulty: 1,
    hasFree: true,
    tags: ['검색', '논문조사', '출처제공'],
    color: 'from-cyan-600 to-blue-800',
    lastReviewed: REVIEWED_AT,
    quickFilters: ['free', 'beginner'],
  },
  {
    id: 'zapier',
    name: 'Zapier',
    nameKo: '재피어',
    description: '수천 개의 앱(지메일, 슬랙 등)을 AI와 연동하여 반복 업무를 자동화하는 도구. 코딩 없이 워크플로우를 구성할 수 있습니다.',
    url: 'https://zapier.com',
    category: '업무 생산성',
    categoryIcon: '⚡',
    difficulty: 3,
    hasFree: true,
    tags: ['업무자동화', '연동', '워크플로우'],
    color: 'from-orange-500 to-red-600',
    lastReviewed: REVIEWED_AT,
    quickFilters: ['free'],
  },

  // 이미지 생성
  {
    id: 'midjourney',
    name: 'Midjourney',
    nameKo: '미드저니',
    description: '뛰어난 퀄리티의 이미지 생성 AI. 2024년부터 웹 인터페이스도 제공하며, 예술적 스타일 표현에 특히 강합니다.',
    url: 'https://www.midjourney.com',
    category: '이미지 생성',
    categoryIcon: '🎨',
    difficulty: 2,
    hasFree: false,
    tags: ['고퀄리티', '예술', '디자인'],
    color: 'from-purple-600 to-fuchsia-800',
    lastReviewed: REVIEWED_AT,
    quickFilters: ['image'],
  },
  {
    id: 'dalle3',
    name: 'DALL-E 3',
    nameKo: '달리 3',
    description: 'ChatGPT 안에서 바로 사용할 수 있는 이미지 생성 AI. 복잡한 지시도 잘 반영하며 텍스트 삽입이 가능합니다.',
    url: 'https://chatgpt.com',
    category: '이미지 생성',
    categoryIcon: '🖼️',
    difficulty: 1,
    hasFree: false,
    tags: ['쉽다', 'ChatGPT연동', '스토리보드'],
    color: 'from-rose-600 to-pink-800',
    lastReviewed: REVIEWED_AT,
    quickFilters: ['image', 'beginner'],
  },
  {
    id: 'leonardo',
    name: 'Leonardo.Ai',
    nameKo: '레오나르도 AI',
    description: '게임 에셋·캐릭터 디자인에 특화된 이미지 생성 AI. 무료 크레딧을 매일 제공해 부담 없이 시작할 수 있습니다.',
    url: 'https://leonardo.ai',
    category: '이미지 생성',
    categoryIcon: '🖌️',
    difficulty: 2,
    hasFree: true,
    tags: ['무료크레딧', '게임아트', '다양한모델'],
    color: 'from-fuchsia-600 to-purple-900',
    lastReviewed: REVIEWED_AT,
    quickFilters: ['free', 'image'],
  },

  // 영상/오디오
  {
    id: 'suno',
    name: 'Suno AI',
    nameKo: '수노 AI',
    description: '가사와 스타일만 적으면 보컬이 들어간 완성된 노래를 만들어줍니다. 음악을 전혀 몰라도 바로 시작할 수 있습니다.',
    url: 'https://suno.com',
    category: '영상/오디오',
    categoryIcon: '🎵',
    difficulty: 1,
    hasFree: true,
    tags: ['작곡', '음악생성', '보컬'],
    color: 'from-yellow-500 to-orange-600',
    lastReviewed: REVIEWED_AT,
    quickFilters: ['free', 'beginner', 'video'],
  },
  {
    id: 'udio',
    name: 'Udio',
    nameKo: '우디오',
    description: '고품질 음악 생성 AI. 악기 소리와 보컬이 선명하며, 장르·분위기를 세밀하게 제어할 수 있습니다.',
    url: 'https://www.udio.com',
    category: '영상/오디오',
    categoryIcon: '🎧',
    difficulty: 1,
    hasFree: true,
    tags: ['고음질', '작곡', '음악생성'],
    color: 'from-blue-500 to-indigo-600',
    lastReviewed: REVIEWED_AT,
    quickFilters: ['free', 'video'],
  },
  {
    id: 'runway',
    name: 'Runway Gen-3',
    nameKo: '런웨이 젠3',
    description: '텍스트·이미지로 고품질 영상을 생성하는 AI 영상 툴. Gen-3 Alpha 모델로 이전보다 훨씬 자연스러운 동작을 구현합니다.',
    url: 'https://runwayml.com',
    category: '영상/오디오',
    categoryIcon: '🎥',
    difficulty: 2,
    hasFree: true,
    tags: ['영상생성', '특수효과', '영화'],
    color: 'from-teal-500 to-emerald-700',
    lastReviewed: REVIEWED_AT,
    quickFilters: ['free', 'video'],
  },
  {
    id: 'heygen',
    name: 'HeyGen',
    nameKo: '헤이젠',
    description: '사진과 텍스트만으로 말하는 아바타 영상을 제작합니다. 다국어 립싱크 기능이 있어 글로벌 콘텐츠 제작에 유용합니다.',
    url: 'https://www.heygen.com',
    category: '영상/오디오',
    categoryIcon: '👤',
    difficulty: 2,
    hasFree: true,
    tags: ['아바타', '영상제작', '립싱크'],
    color: 'from-violet-500 to-purple-600',
    lastReviewed: REVIEWED_AT,
    quickFilters: ['free', 'video'],
  },

  // 문서/글쓰기
  {
    id: 'notion-ai',
    name: 'Notion AI',
    nameKo: '노션 AI',
    description: '노션 안에서 문서 요약, 글 다듬기, 할 일 추출을 도와주는 AI. 이미 노션을 쓰고 있다면 가장 자연스럽게 연동됩니다.',
    url: 'https://www.notion.so/product/ai',
    category: '문서/글쓰기',
    categoryIcon: '📝',
    difficulty: 2,
    hasFree: false,
    tags: ['노션', '문서요약', '아이디어'],
    color: 'from-stone-600 to-stone-800',
    lastReviewed: REVIEWED_AT,
    quickFilters: [],
  },
  {
    id: 'gamma',
    name: 'Gamma',
    nameKo: '감마',
    description: '주제만 입력하면 1분 안에 디자인된 프레젠테이션을 만들어줍니다. PPT, 웹페이지, 문서 형식 모두 지원합니다.',
    url: 'https://gamma.app',
    category: '문서/글쓰기',
    categoryIcon: '📊',
    difficulty: 1,
    hasFree: true,
    tags: ['PPT', '발표자료', '디자인'],
    color: 'from-violet-600 to-purple-800',
    lastReviewed: REVIEWED_AT,
    quickFilters: ['free', 'beginner'],
  },
  {
    id: 'wrtn',
    name: 'Wrtn',
    nameKo: '뤼튼',
    description: '한국어 특화 AI 글쓰기 서비스. 자기소개서, 블로그, 마케팅 문구 등을 한국어 맥락에 맞게 작성해 줍니다.',
    url: 'https://wrtn.ai',
    category: '문서/글쓰기',
    categoryIcon: '✍️',
    difficulty: 1,
    hasFree: true,
    tags: ['한국어', '카피라이팅', '무료'],
    color: 'from-pink-500 to-rose-600',
    lastReviewed: REVIEWED_AT,
    quickFilters: ['free', 'beginner', 'korean'],
  },

  // 코딩/개발
  {
    id: 'cursor',
    name: 'Cursor',
    nameKo: '커서',
    description: 'AI가 내장된 코드 에디터. 코드 자동 완성, 버그 수정, 전체 기능 구현까지 자연어로 지시할 수 있습니다.',
    url: 'https://cursor.com',
    category: '코딩/개발',
    categoryIcon: '💻',
    difficulty: 3,
    hasFree: true,
    tags: ['코딩', '개발자', 'VSCode호환'],
    color: 'from-slate-700 to-slate-900',
    lastReviewed: REVIEWED_AT,
    quickFilters: ['free', 'code'],
  },
  {
    id: 'v0-dev',
    name: 'v0.dev',
    nameKo: '브이제로',
    description: 'Vercel이 만든 UI 생성 AI. 프롬프트를 입력하면 React + Tailwind 코드를 바로 만들어 주고 즉시 미리볼 수 있습니다.',
    url: 'https://v0.dev',
    category: '코딩/개발',
    categoryIcon: '✨',
    difficulty: 2,
    hasFree: true,
    tags: ['프론트엔드', 'UI생성', '디자인'],
    color: 'from-zinc-800 to-zinc-950',
    lastReviewed: REVIEWED_AT,
    quickFilters: ['free', 'code'],
  },
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    nameKo: '깃허브 코파일럿',
    description: '업계 표준 AI 코딩 도우미. 코드 작성 중 다음 줄이나 함수 전체를 자동으로 제안하며, VS Code 등 주요 에디터를 지원합니다.',
    url: 'https://github.com/features/copilot',
    category: '코딩/개발',
    categoryIcon: '🐙',
    difficulty: 2,
    hasFree: false,
    tags: ['자동완성', '표준도구', '개발자'],
    color: 'from-gray-700 to-gray-900',
    lastReviewed: REVIEWED_AT,
    quickFilters: ['code'],
  },

  // 하드웨어/설계
  {
    id: 'flux-ai',
    name: 'Flux.ai',
    nameKo: '플럭스',
    description: '하드웨어 엔지니어를 위한 AI 기반 PCB 설계 툴. 브라우저에서 회로 배선을 돕고, AI 어시스턴트가 설계 조언을 제공합니다.',
    url: 'https://www.flux.ai',
    category: '하드웨어/설계',
    categoryIcon: '⚙️',
    difficulty: 3,
    hasFree: true,
    tags: ['PCB', '회로설계', '하드웨어'],
    color: 'from-blue-700 to-indigo-900',
    lastReviewed: REVIEWED_AT,
    quickFilters: ['free'],
  },
  {
    id: 'fusion360-gen',
    name: 'Fusion 360 AI',
    nameKo: '퓨전 360 (제너레이티브 디자인)',
    description: '하중·소재 조건을 입력하면 AI가 최적의 3D 형상을 자동으로 생성해 제안합니다. 경량화·내구성 설계에 효과적입니다.',
    url: 'https://www.autodesk.com/products/fusion-360/generative-design',
    category: '하드웨어/설계',
    categoryIcon: '📐',
    difficulty: 3,
    hasFree: false,
    tags: ['3D모델링', 'CAD', '기구설계'],
    color: 'from-orange-600 to-red-800',
    lastReviewed: REVIEWED_AT,
    quickFilters: [],
  },

  // 논문/연구
  {
    id: 'scispace',
    name: 'SciSpace',
    nameKo: '사이스페이스',
    description: '전 세계 논문을 검색하고 PDF를 업로드하면, 어려운 수식이나 표도 AI가 알기 쉽게 설명해 줍니다.',
    url: 'https://typeset.io',
    category: '논문/연구',
    categoryIcon: '🔬',
    difficulty: 2,
    hasFree: true,
    tags: ['논문검색', '수식설명', '연구자'],
    color: 'from-emerald-600 to-cyan-800',
    lastReviewed: REVIEWED_AT,
    quickFilters: ['free'],
  },
  {
    id: 'consensus',
    name: 'Consensus',
    nameKo: '컨센서스',
    description: '논문 기반 AI 검색 엔진. 연구 질문을 던지면 관련 논문들의 결론을 종합해 근거 중심의 답변을 제공합니다.',
    url: 'https://consensus.app',
    category: '논문/연구',
    categoryIcon: '🎓',
    difficulty: 1,
    hasFree: true,
    tags: ['논문검색', '팩트체크', '근거제시'],
    color: 'from-indigo-500 to-blue-700',
    lastReviewed: REVIEWED_AT,
    quickFilters: ['free', 'beginner'],
  },
  {
    id: 'chatpdf',
    name: 'ChatPDF',
    nameKo: '챗PDF',
    description: 'PDF를 업로드하면 내용에 대해 자유롭게 질문할 수 있습니다. 어느 페이지에 있는 내용인지 출처도 함께 알려줍니다.',
    url: 'https://www.chatpdf.com',
    category: '논문/연구',
    categoryIcon: '📄',
    difficulty: 1,
    hasFree: true,
    tags: ['PDF요약', '문서대화', '대학생'],
    color: 'from-red-500 to-rose-700',
    lastReviewed: REVIEWED_AT,
    quickFilters: ['free', 'beginner'],
  },
];
